<a href="https://colab.research.google.com/github/19206406/learning_PyTorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals


In [78]:
print("Hello I'm excited to learn PyTorch!")

Hello I'm excited to learn PyTorch!


In [79]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


##  Introduction to Tensors

### Creating tensors

PyTorch Tensor doc: https://docs.pytorch.org/docs/stable/tensors.html

In [80]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [81]:
scalar.ndim

0

In [82]:
# Get tensor back as Python int
scalar.item()

7

In [83]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [84]:
vector.ndim

1

In [85]:
vector.shape

torch.Size([2])

In [86]:
# Matrix

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [87]:
MATRIX.ndim

2

In [88]:
MATRIX[1]

tensor([ 9, 10])

In [89]:
MATRIX.shape

torch.Size([2, 2])

In [90]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [91]:
TENSOR.ndim

3

In [92]:
TENSOR.shape

torch.Size([1, 3, 3])

In [93]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Practice tensors

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they wich tensors full of random numbers and then adjust those random numbers to better represent the data

`Star with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [94]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(2, 4)
random_tensor

tensor([[0.0113, 0.1582, 0.7130, 0.7754],
        [0.7457, 0.0251, 0.4055, 0.1125]])

In [95]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 214)) # height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 214]), 3)

In [96]:
torch.rand(3, 3)

tensor([[0.2297, 0.9149, 0.5115],
        [0.1993, 0.0689, 0.0187],
        [0.6634, 0.3319, 0.7628]])

### Zeros and ones

In [97]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(2, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [98]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [99]:
ones.dtype

torch.float32

In [100]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [101]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Practica con random tensors


### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [103]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [104]:
float_32_tensor.dtype

torch.float32

In [105]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [106]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [107]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [108]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attribute)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [109]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6738, 0.7820, 0.2197, 0.2718],
        [0.3198, 0.8949, 0.3350, 0.8516],
        [0.5542, 0.8033, 0.2004, 0.2117]])

In [110]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [111]:
some_tensor.size()

torch.Size([3, 4])

In [112]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6738, 0.7820, 0.2197, 0.2718],
        [0.3198, 0.8949, 0.3350, 0.8516],
        [0.5542, 0.8033, 0.2004, 0.2117]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [113]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [114]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [115]:
tensor

tensor([1, 2, 3])

In [116]:
# Substract ten
tensor - 10

tensor([-9, -8, -7])

In [117]:
# Try out PyTorch in-built functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [118]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)


there are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work  

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [119]:
torch.matmul(torch.rand(10, 10), torch.rand(10, 10))

tensor([[1.9996, 2.3919, 1.3988, 1.2927, 2.2651, 2.8469, 2.0988, 2.1130, 1.8791,
         1.6795],
        [2.2950, 1.4585, 1.6324, 0.7929, 1.9402, 2.3341, 2.2897, 1.9857, 2.0490,
         1.9844],
        [2.7945, 2.5455, 2.0615, 1.7476, 2.6198, 3.3129, 2.5450, 2.8396, 2.6096,
         2.4581],
        [2.8532, 2.4563, 1.8046, 1.5417, 2.7286, 3.4344, 2.8623, 2.7522, 2.4431,
         2.3237],
        [3.4714, 3.3824, 2.5490, 2.3549, 3.7720, 3.9372, 3.4216, 3.7747, 3.1516,
         3.1357],
        [2.1224, 1.9179, 2.2387, 1.5253, 2.2219, 2.9779, 2.4828, 2.0630, 2.6337,
         2.4250],
        [3.1842, 3.0990, 2.4831, 2.0036, 3.2837, 3.6913, 3.0039, 3.2294, 3.0418,
         2.9102],
        [2.6547, 2.6481, 1.8284, 1.7396, 2.6868, 3.6942, 2.7631, 2.7131, 2.5804,
         2.2553],
        [1.8187, 2.0393, 2.0769, 1.6323, 2.1370, 2.7000, 2.1585, 2.0200, 2.4628,
         2.2725],
        [1.4032, 1.4749, 1.4820, 1.2588, 1.7145, 2.1912, 1.8455, 1.6038, 1.7115,
         1.6239]])

In [120]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [121]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [122]:
tensor

tensor([1, 2, 3])

In [123]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [124]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.41 ms, sys: 0 ns, total: 1.41 ms
Wall time: 2.46 ms


In [125]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 422 µs, sys: 0 ns, total: 422 µs
Wall time: 472 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [126]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul
# torch.matmul(tensor_A * tensor_B)

In [127]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.


In [128]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [129]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [130]:
# the matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.t = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")

output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.t = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [131]:
 # Create a tensor
 x = torch.arange(0, 100, 10)
 x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [132]:
# Find the min
torch.min(x), x.max()

(tensor(0), tensor(90))

In [133]:
# Tind the max
torch.max(x), x.max

(tensor(90), <function Tensor.max>)

In [134]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [135]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [136]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [137]:
# Find the position in tensor that has the minium value with argmin() -> returns index position of target tensor where the min value accours
x.argmin()

tensor(0)

In [138]:
x[0]

tensor(0)

In [139]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [140]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensor on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way



In [140]:
# Let's create a tensor
import torch