<a href="https://colab.research.google.com/github/19206406/learning_PyTorch/blob/main/00_pytorch_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness).

1. The documentation on `torch.Tensor`
2. The documentation on `torch.cuda`


In [3]:
# Already

### 2. Create a random tensor with shape (7, 7)

In [10]:
import torch

# tensor between 0 and 1
x = torch.rand(7, 7)
print(x)

# tensor with others values
y = torch.round(torch.rand(3, 4) * 10)
print(y)

tensor([[0.1263, 0.2782, 0.0572, 0.2270, 0.6845, 0.4937, 0.4780],
        [0.1349, 0.2327, 0.6638, 0.4221, 0.8287, 0.3775, 0.0355],
        [0.8457, 0.0046, 0.1349, 0.7792, 0.5145, 0.0378, 0.3023],
        [0.6869, 0.8413, 0.0862, 0.1520, 0.4240, 0.4091, 0.4033],
        [0.3770, 0.2047, 0.8303, 0.9434, 0.1611, 0.4366, 0.7030],
        [0.9001, 0.4547, 0.4895, 0.9369, 0.4589, 0.4389, 0.3447],
        [0.5728, 0.2044, 0.7196, 0.2289, 0.0032, 0.1294, 0.7896]])
tensor([[7., 0., 7., 1.],
        [6., 0., 6., 3.],
        [5., 2., 7., 4.]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [23]:
y = torch.rand(1, 7)

# multiplication
# multiplication = torch.matmul(x, y) - generate error
multiplication = torch.matmul(x, torch.t(y)) # Success
multiplication_2 = torch.matmul(x, y.T) # Success - other form

print(multiplication)
print("-----------------------------------")
print(multiplication_2)


tensor([[1.1312],
        [1.2543],
        [1.4483],
        [1.6085],
        [1.8497],
        [2.1717],
        [1.3549]])
-----------------------------------
tensor([[1.1312],
        [1.2543],
        [1.4483],
        [1.6085],
        [1.8497],
        [2.1717],
        [1.3549]])


### 4. Set the random seed to 0 and do 2 & 3 over again.
**The output should be:**

```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [26]:
torch.manual_seed(0)
x_2 = torch.rand(7, 7)
y_2 = torch.rand(1, 7)

result = torch.matmul(x_2, y_2.T)
result, result.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)