<a href="https://colab.research.google.com/github/19206406/learning_PyTorch/blob/main/00_pytorch_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness).

1. The documentation on `torch.Tensor`
2. The documentation on `torch.cuda`


In [2]:
# Already

### 2. Create a random tensor with shape (7, 7)

In [3]:
import torch

# tensor between 0 and 1
x = torch.rand(7, 7)
print(x)

# tensor with others values
y = torch.round(torch.rand(3, 4) * 10)
print(y)

tensor([[0.5832, 0.7831, 0.0239, 0.8114, 0.5299, 0.9152, 0.1247],
        [0.2324, 0.8947, 0.5459, 0.4400, 0.9539, 0.8278, 0.6693],
        [0.5584, 0.4387, 0.8388, 0.5699, 0.3992, 0.5567, 0.7409],
        [0.3265, 0.9864, 0.1740, 0.5287, 0.6707, 0.1231, 0.3352],
        [0.9611, 0.6061, 0.1678, 0.1698, 0.0531, 0.7601, 0.1013],
        [0.4795, 0.2636, 0.2450, 0.6550, 0.6236, 0.4087, 0.2047],
        [0.3622, 0.5362, 0.8343, 0.1321, 0.8215, 0.5374, 0.4923]])
tensor([[7., 3., 1., 9.],
        [1., 3., 9., 3.],
        [8., 0., 3., 2.]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [4]:
y = torch.rand(1, 7)

# multiplication
# multiplication = torch.matmul(x, y) - generate error
multiplication = torch.matmul(x, torch.t(y)) # Success
multiplication_2 = torch.matmul(x, y.T) # Success - other form

print(multiplication)
print("-----------------------------------")
print(multiplication_2)


tensor([[1.9754],
        [1.7734],
        [1.8890],
        [1.1946],
        [1.6046],
        [1.5444],
        [1.4191]])
-----------------------------------
tensor([[1.9754],
        [1.7734],
        [1.8890],
        [1.1946],
        [1.6046],
        [1.5444],
        [1.4191]])


### 4. Set the random seed to 0 and do 2 & 3 over again.
**The output should be:**

```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
torch.manual_seed(0)
x_2 = torch.rand(7, 7)
y_2 = torch.rand(1, 7)

result = torch.matmul(x_2, y_2.T)
result, result.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [6]:
if (torch.cuda.is_available()):
  torch.cuda.manual_seed(5)
else:
  print("Nothing")

### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```


In [45]:
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"

x_1 = torch.rand(size=(2, 3)).to(device)
x_2 = torch.rand(size=(2, 3)).to(device)

x_1, x_2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

```
The output should look like:

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [46]:
mult = torch.matmul(x_1, x_2.T)
mult, mult.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [25]:
mult.max(), mult.min()

(tensor(0.7668, device='cuda:0'), tensor(0.2786, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [30]:
mult.argmin(), mult.argmax()

(tensor(0, device='cuda:0'), tensor(1, device='cuda:0'))

### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

```
The output should look like:

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [37]:
torch.manual_seed(7)
first_tensor = torch.rand(1, 1, 1, 10)

torch.manual_seed(7)
second_tensor = torch.rand(10)

print(first_tensor, first_tensor.shape)
print("--------------------------------------------------------------------------")
print(second_tensor, second_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
--------------------------------------------------------------------------
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
